version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/smoothswipe-ui
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: buildscript/dummy.sh
      timeout: 5
  AfterInstall:
    - location: buildscript/build.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: buildscript/change_permission.sh
      timeout: 60
  ValidateService:
    - location: buildscript/build.sh
      timeout: 120

